name: Move to youth

on:
  schedule:
    - cron: "0 18 * * 1" # 6 PM UTC every Monday
  workflow_dispatch: # Allows manual triggering

jobs:
  send_post_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Log runner's IP address
        run: curl https://ifconfig.me

      - name: Move Youths
        env:
          DO_USER: ${{ secrets.DO_USER }}
          DO_PASS: ${{ secrets.DO_PASS }}
          COOKIE: ${{ secrets.COOKIE }}
          PAYLOAD: ${{ vars.MOVE_TO_YOUTH }}
        run: node scripts/moveplayers.js
